apiVersion: v1
kind: Service
metadata:
  name: royalafg-docs
  namespace: royalafg
spec:
  selector:
    app: royalafg-docs
  ports:
    - name: web
      port: 80
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: royalafg-docs
  namespace: royalafg
spec:
  rules:
    - host: troyalafg.games
      http:
        paths:
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: royalafg-docs
                port:
                  number: 80
    - host: royalafg.games
      http:
        paths:
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: royalafg-docs
                port:
                  number: 80
  tls:
    - secretName: docs-tls-cert
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: royalafg-docs
  namespace: royalafg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: royalafg-docs
  namespace: royalafg
spec:
  selector:
    matchLabels:
      app: royalafg-docs
  replicas: 1
  template:
    metadata:
      labels:
        app: royalafg-docs
    spec:
      containers:
        - name: royalafg-docs
          image: "docker.io/johnnys318/royalafg-docs:latest"
          resources:
            limits:
              memory: "20Mi"
              cpu: "250m"
            requests:
              memory: 10Mi
              cpu: 100m
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: royalafg-docs-config
              mountPath: "/etc/royalafg-docs"

      volumes:
        - name: royalafg-docs-config
          configMap:
            name: royalafg-docs
